package com.study.module.system.guardian.service.impl;
import com.baomidou.mybatisplus.core.conditions.Wrapper;
import com.study.module.system.guardian.dto.response.GuardianWeeklyReportResp;
import com.study.module.system.review.entity.ReviewRecord; import com.study.module.system.review.service.ReviewItemService; import com.study.module.system.review.service.ReviewRecordService;
import com.study.module.system.user.entity.User; import com.study.module.system.user.service.UserService; import com.study.module.system.wrongquestion.constants.WrongQuestionStatus; import com.study.module.system.wrongquestion.entity.WrongQuestion; import com.study.module.system.wrongquestion.service.WrongQuestionService;
import org.junit.jupiter.api.Test; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.InjectMocks; import org.mockito.Mock; import org.mockito.junit.jupiter.MockitoExtension;
import java.time.LocalDateTime; import java.util.Arrays; import static org.junit.jupiter.api.Assertions.assertEquals; import static org.mockito.ArgumentMatchers.any; import static org.mockito.Mockito.when;
/** 周报指标只基于聚合学习数据计算。 */
@ExtendWith(MockitoExtension.class) class GuardianWeeklyReportServiceImplTest {
 @Mock private UserService userService; @Mock private WrongQuestionService wrongQuestionService; @Mock private ReviewRecordService reviewRecordService; @Mock private ReviewItemService reviewItemService; @InjectMocks private GuardianWeeklyReportServiceImpl service;
 @Test void shouldBuildWeeklyMetrics() { User user = new User(); user.setRealName("学生A"); WrongQuestion created = new WrongQuestion(); created.setCreateTime(LocalDateTime.now().minusDays(1)); created.setUpdateTime(LocalDateTime.now().minusDays(1)); created.setStatus(WrongQuestionStatus.CORRECTED); ReviewRecord correct = new ReviewRecord(); correct.setIsCorrect(1); correct.setIsIndependent(1); ReviewRecord wrong = new ReviewRecord(); wrong.setIsCorrect(0); wrong.setIsIndependent(1); ReviewRecord copied = new ReviewRecord(); copied.setIsCorrect(1); copied.setIsIndependent(0); when(userService.getById(1L)).thenReturn(user); when(wrongQuestionService.list(any(Wrapper.class))).thenReturn(Arrays.asList(created)); when(reviewRecordService.list(any(Wrapper.class))).thenReturn(Arrays.asList(correct, wrong, copied)); when(reviewItemService.count(any(Wrapper.class))).thenReturn(2L); GuardianWeeklyReportResp report = service.buildWeeklyReport(1L); assertEquals(1, report.getNewWrongQuestionCount()); assertEquals(1, report.getCorrectedCount()); assertEquals(2, report.getEffectiveReviewCount()); assertEquals(50, report.getRetentionRate()); assertEquals(2, report.getOverdueCount()); }
}
