import request from '@/utils/request'

export const questionBankPageList = params => request({ url: '/api/questionBank/questionBankPageList', method: 'get', params })
export const questionBankDetail = params => request({ url: '/api/questionBank/questionBankDetail', method: 'get', params })
export const saveQuestionBank = data => request({ url: '/api/questionBank/saveQuestionBank', method: 'post', data })
export const deleteQuestionBank = data => request({ url: '/api/questionBank/deleteQuestionBank', method: 'post', data })
export const reviewQuestionBank = data => request({ url: '/api/questionBank/reviewQuestionBank', method: 'post', data })
export const duplicateQuestionList = data => request({ url: '/api/questionBank/duplicateQuestionList', method: 'post', data })
export const duplicateQuestionHistory = params => request({ url: '/api/questionBank/duplicateQuestionHistory', method: 'get', params })
export const cleanDuplicateQuestion = data => request({ url: '/api/questionBank/cleanDuplicateQuestion', method: 'post', data })
export const mergeDuplicateQuestion = data => request({ url: '/api/questionBank/mergeDuplicateQuestion', method: 'post', data })
export const batchReviewQuestionBank = data => request({ url: '/api/questionBank/batchReviewQuestionBank', method: 'post', data })
export const knowledgePointList = params => request({ url: '/api/knowledgePoint/knowledgePointList', method: 'get', params })
export const knowledgePointTree = params => request({ url: '/api/knowledgePoint/knowledgePointTree', method: 'get', params })
export const saveKnowledgePoint = data => request({ url: '/api/knowledgePoint/saveKnowledgePoint', method: 'post', data })
export const deleteKnowledgePoint = data => request({ url: '/api/knowledgePoint/deleteKnowledgePoint', method: 'post', data })
export const knowledgePointPrerequisiteList = params => request({ url: '/api/knowledgePoint/knowledgePointPrerequisiteList', method: 'get', params })
export const saveKnowledgePointPrerequisite = data => request({ url: '/api/knowledgePoint/saveKnowledgePointPrerequisite', method: 'post', data })
export const questionVariantTemplateList = params => request({ url: '/api/questionVariant/questionVariantTemplateList', method: 'get', params })
export const saveQuestionVariantTemplate = data => request({ url: '/api/questionVariant/saveQuestionVariantTemplate', method: 'post', data })
export const generateQuestionVariant = data => request({ url: '/api/questionVariant/generateQuestionVariant', method: 'post', data })
export const questionBankVersionList = params => request({ url: '/api/questionBank/questionBankVersionList', method: 'get', params })
export const questionBankReviewHistory = params => request({ url: '/api/questionBank/questionBankReviewHistory', method: 'get', params })
export const governQuestionContent = data => request({ url: '/api/questionBank/governQuestionContent', method: 'post', data })
export const rollbackQuestionBankVersion = data => request({ url: '/api/questionBank/rollbackQuestionBankVersion', method: 'post', data })
export const questionContentGovernanceList = params => request({ url: '/api/questionBank/questionContentGovernanceList', method: 'get', params })
export const importQuestionBankFile = data => request({ url: '/api/questionBank/importQuestionBankFile', method: 'post', data })
export const similarQuestionList = data => request({ url: '/api/questionRecommendationLog/similarQuestionList', method: 'post', data })
export const submitQuestionPractice = data => request({ url: '/api/questionRecommendationLog/submitQuestionPractice', method: 'post', data })
export const viewQuestionPracticeAnswer = data => request({ url: '/api/questionRecommendationLog/viewQuestionPracticeAnswer', method: 'post', data })
export const createQuestionPracticeAppeal = data => request({ url: '/api/questionPracticeAppeal/createQuestionPracticeAppeal', method: 'post', data })
export const questionPracticeAppealList = params => request({ url: '/api/questionPracticeAppeal/questionPracticeAppealList', method: 'get', params })
export const reviewQuestionPracticeAppeal = data => request({ url: '/api/questionPracticeAppeal/reviewQuestionPracticeAppeal', method: 'post', data })
export const reportQuestion = data => request({ url: '/api/questionReport/reportQuestion', method: 'post', data })
export const questionReportPageList = params => request({ url: '/api/questionReport/questionReportPageList', method: 'get', params })
export const handleQuestionReport = data => request({ url: '/api/questionReport/handleQuestionReport', method: 'post', data })
export const questionPracticeStatistics = () => request({ url: '/api/questionRecommendationLog/questionPracticeStatistics', method: 'get' })
export const questionPracticeHistoryPageList = params => request({ url: '/api/questionRecommendationLog/questionPracticeHistoryPageList', method: 'get', params })
export const questionExperimentDetail = () => request({ url: '/api/questionExperiment/questionExperimentDetail', method: 'get' })
export const saveQuestionExperiment = data => request({ url: '/api/questionExperiment/saveQuestionExperiment', method: 'post', data })
export const questionExperimentHistory = () => request({ url: '/api/questionExperiment/questionExperimentHistory', method: 'get' })
