package com.study.module.system.guardian.service.impl;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.study.common.core.enums.ErrorCodeConstants;
import com.study.common.core.exception.LogicException;
import com.study.module.system.guardian.dto.response.GuardianWeeklyReportResp;
import com.study.module.system.guardian.service.GuardianAccessAuditService;
import com.study.module.system.guardian.service.GuardianBindingService;
import com.study.module.system.guardian.service.GuardianWeeklyReportService;
import com.study.module.system.review.constants.ReviewItemStatus;
import com.study.module.system.review.constants.ReviewMetricPolicy;
import com.study.module.system.review.entity.ReviewItem; import com.study.module.system.review.entity.ReviewRecord;
import com.study.module.system.review.service.ReviewItemService; import com.study.module.system.review.service.ReviewRecordService;
import com.study.module.system.user.entity.User; import com.study.module.system.user.service.UserService;
import com.study.module.system.wrongquestion.constants.WrongQuestionStatus; import com.study.module.system.wrongquestion.entity.WrongQuestion; import com.study.module.system.wrongquestion.service.WrongQuestionService;
import com.yunshang.budget.common.security.utils.AccountUtils; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.stereotype.Service; import org.springframework.util.StringUtils;
import java.time.LocalDate; import java.time.LocalDateTime; import java.util.List;
@Service public class GuardianWeeklyReportServiceImpl implements GuardianWeeklyReportService {
 @Autowired private GuardianBindingService guardianBindingService; @Autowired private GuardianAccessAuditService auditService; @Autowired private UserService userService; @Autowired private WrongQuestionService wrongQuestionService; @Autowired private ReviewRecordService reviewRecordService; @Autowired private ReviewItemService reviewItemService;
 @Override public GuardianWeeklyReportResp guardianWeeklyReport(Long studentUserId) { if (!guardianBindingService.canCurrentGuardianAccessStudent(studentUserId)) throw new LogicException(ErrorCodeConstants.GUARDIAN_BINDING_NOT_EXIST); GuardianWeeklyReportResp report = buildWeeklyReport(studentUserId); auditService.record(null, studentUserId, AccountUtils.getUserId(), AccountUtils.getUserId(), "WEEKLY_REPORT_VIEWED", "SUCCESS", "查看家长周报汇总"); return report; }
 @Override public GuardianWeeklyReportResp buildWeeklyReport(Long studentUserId) { LocalDateTime now = LocalDateTime.now(), start = now.minusDays(7); List<WrongQuestion> questions = wrongQuestionService.list(new LambdaQueryWrapper<WrongQuestion>().eq(WrongQuestion::getCreateId, studentUserId)); List<ReviewRecord> records = reviewRecordService.list(new LambdaQueryWrapper<ReviewRecord>().eq(ReviewRecord::getUserId, studentUserId).ge(ReviewRecord::getReviewTime, start).lt(ReviewRecord::getReviewTime, now)); long judged = records.stream().filter(ReviewMetricPolicy::isEffectiveReview).count(); long correct = records.stream().filter(ReviewMetricPolicy::isIndependentCorrect).count(); int overdue = (int) reviewItemService.count(new LambdaQueryWrapper<ReviewItem>().eq(ReviewItem::getUserId, studentUserId).eq(ReviewItem::getItemStatus, ReviewItemStatus.NORMAL).lt(ReviewItem::getNextReviewTime, LocalDate.now().atStartOfDay())); User user = userService.getById(studentUserId); GuardianWeeklyReportResp report = new GuardianWeeklyReportResp(); report.setStudentUserId(studentUserId); report.setStudentName(user == null ? "学生" : (StringUtils.hasText(user.getRealName()) ? user.getRealName() : user.getUserName())); report.setNewWrongQuestionCount((int) questions.stream().filter(item -> item.getCreateTime() != null && !item.getCreateTime().isBefore(start)).count()); report.setCorrectedCount((int) questions.stream().filter(item -> item.getUpdateTime() != null && !item.getUpdateTime().isBefore(start) && item.getStatus() != null && item.getStatus() >= WrongQuestionStatus.CORRECTED).count()); report.setEffectiveReviewCount((int) judged); report.setRetentionRate(ReviewMetricPolicy.percent(correct, judged)); report.setOverdueCount(overdue); report.setNextWeekSuggestion(overdue > 0 ? "优先完成" + overdue + "个逾期复习任务，再安排新的练习。" : report.getEffectiveReviewCount() < 3 ? "下周可安排至少3次独立复习，帮助形成稳定保持率。" : "保持当前节奏，并优先订正新错题。"); return report; }
}
